export const siteConfig = {
  name: "Telvis",
  url: "https://telvis.uk",
  primaryKeyword: "IPTV UK",
  title: "Telvis IPTV UK | Subscription from £9.99 with 24-Hour Trial",
  description:
    "Try Telvis IPTV on your own device for 24 hours. Paid plans start at £9.99, with setup guides, WhatsApp support and a seven-day refund on eligible orders.",
  h1: "Telvis IPTV UK – Subscription from £9.99 with Free 24-Hour Trial",
  contentUpdated: "2026-09-24",
} as const;

export const routes = {
  home: "/",
  trial: "/free-trial",
  plans: "/plans",
  plansHash: "/#plans",
  about: "/about",
  installation: "/installation-guide",
  reviews: "/reviews",
  contact: "/contact",
  refund: "/refund-policy",
  privacy: "/privacy-policy",
  terms: "/terms",
} as const;

export const supportConfig = {
  email: "support@telvis.uk",
  whatsapp: "+44 7482 794475",
  whatsappUrl: "https://wa.me/447482794475",
  downloaderCode: "TELVIS",
} as const;

/** Optimized brand assets served from /public (generated by scripts/generate-brand-icons.mjs). */
export const brandAssets = {
  logo512: "/logo-512.png",
  ogImage: "/og-image.png",
  favicon48: "/favicon-48.png",
  appleTouchIcon: "/apple-touch-icon.png",
  manifest: "/site.webmanifest",
} as const;

export const navLinks = [
  { href: routes.home, label: "Home" },
  { href: routes.plans, label: "Plans" },
  { href: routes.installation, label: "Installation Guide" },
  { href: routes.reviews, label: "Reviews" },
  { href: routes.contact, label: "Contact Us" },
] as const;

export const footerQuickLinks = [
  { href: routes.plans, label: "View Plans" },
  { href: routes.trial, label: "Start Free Trial" },
  { href: "/#faq", label: "FAQ" },
] as const;

export const footerPageLinks = [
  { href: routes.home, label: "Home" },
  { href: routes.about, label: "About Telvis" },
  { href: routes.installation, label: "Installation Guide" },
  { href: routes.reviews, label: "Reviews" },
  { href: routes.contact, label: "Contact Us" },
] as const;

export const footerLegalLinks = [
  { href: routes.refund, label: "Refund Policy" },
  { href: routes.privacy, label: "Privacy Policy" },
  { href: routes.terms, label: "Terms of Use" },
] as const;
